services:
  postgres-prod:
    container_name: postgres_orari
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ADMIN}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER_ADMIN} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5

  adonis_app-prod:
    container_name: adonis_orari
    restart: always
    depends_on:
      postgres-prod:
        condition: service_healthy
    build:
      context: .
      target: production
    ports:
      - '3334:3333'
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      DB_HOST: postgres-prod
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - adonis_app_data:/home/node/app/build/uploads
    command: >
      dumb-init sh -c "node build/ace migration:run --force && node build/server.js"

volumes:
  postgres_volume:
  adonis_app_data:
