version: '3.8'

services:
  postgres:
    container_name: postgres_orari
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ADMIN}
      APP_DB: orarimed
      SECURE_DB: orarimed_secure
      AUDIT_DB: orarimed_audit
      APP_USER: orarimed_app
      SECURE_USER: orarimed_secure
      AUDIT_USER: orarimed_audit
      APP_PASSWORD: ${DB_APP_PASSWORD}
      SECURE_PASSWORD: ${DB_SECURE_PASSWORD}
      AUDIT_PASSWORD: ${DB_AUDIT_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER_ADMIN}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orarimed-network

  adonis_app:
    container_name: adonis_orari
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      target: dev
    ports:
      - '3334:3333'
      - '9230:9229'
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      DB_HOST: postgres
      DB_PORT: 5432
      DB_APP_USER: orarimed_app
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_APP_DATABASE: orarimed
      DB_SECURE_USER: orarimed_secure
      DB_SECURE_PASSWORD: ${DB_SECURE_PASSWORD}
      DB_SECURE_DATABASE: orarimed_secure
      DB_AUDIT_USER: orarimed_audit
      DB_AUDIT_PASSWORD: ${DB_AUDIT_PASSWORD}
      DB_AUDIT_DATABASE: orarimed_audit
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: sh -c "node ace migration:run --connection=primary && node ace migration:run --connection=secure && node ace migration:run --connection=audit && node ace serve --watch"
    networks:
      - orarimed-network

networks:
  orarimed-network:
    driver: bridge

volumes:
  postgres_volume:
