services:
  postgres-prod:
    container_name: postgres_orari
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ADMIN}
      APP_DB: orarimed
      SECURE_DB: orarimed_secure
      AUDIT_DB: orarimed_audit
      APP_USER: orarimed_app
      SECURE_USER: orarimed_secure
      AUDIT_USER: orarimed_audit
      APP_PASSWORD: ${DB_APP_PASSWORD}
      SECURE_PASSWORD: ${DB_SECURE_PASSWORD}
      AUDIT_PASSWORD: ${DB_AUDIT_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER_ADMIN} -d ${AUDIT_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  adonis_app-prod:
    container_name: adonis_orari
    restart: always
    depends_on:
      postgres-prod:
        condition: service_healthy
    build:
      context: .
      target: production
    ports:
      - '3334:3333'
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      DB_HOST: postgres
      DB_PORT: 5432
      DB_APP_USER: orarimed_app
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_APP_DATABASE: orarimed
      DB_SECONDARY_USER: orarimed_secure
      DB_SECONDARY_PASSWORD: ${DB_SECURE_PASSWORD}
      DB_SECONDARY_DATABASE: orarimed_secure
      DB_AUDIT_USER: orarimed_audit
      DB_AUDIT_PASSWORD: ${DB_AUDIT_PASSWORD}
      DB_AUDIT_DATABASE: orarimed_audit
    volumes:
      - adonis_app_data:/home/node/app/build/uploads
    command: >
      dumb-init sh -c "node build/ace.js migration:run --connection=primary && node build/ace.js migration:run --connection=secure && node build/ace.js migration:run --connection=audit && node build/ace.js serve"

volumes:
  postgres_volume:
  adonis_app_data:
